name: Run Lint - The RED Cinemas

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: lint client and server code
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm install
          npm run lint-client
