<<<<<<< HEAD
name: TheREDCinemas
=======
name: TheREDCinemas client
>>>>>>> 07d42df9f35b3b4de8bae8e75b56a8c24227c224

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Start installing
      - run: npm install
      - name: Start Testing
      - run: npm test
